// <auto-generated />
namespace QuestionAndAnswer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class QustionValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QustionValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201507031220027_QustionValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
